### ISSUE TITLE
How to run on startup?

### ISSUE THREAD

**Issue by lifeBalance** [ViRb3/SylphyHornEx#14]
Congrats for the awesome app. I tried to add it to the startup folder but it doesn't start after I reboot.

**Comment by ViRb3** [comment]
> I can't access the GUI either, clicking on the executable only launch it in the background, so I can't change the shortcuts

Double-click on the icon in your tray. That will show the GUI.

> I tried to add it to the startup folder but it doesn't start after I reboot.

Use the GUI option for startup.

**Comment by lifeBalance** [comment]
Great, thanks a lot. You should get the app in the Windows store, it blows my mind how this essential feature is not part of Windows.

**Comment by ViRb3** [comment]
It's not as stable as I would want it for a Windows Store release, but maybe that'll happen one day, or (preferrably) this project will get integrrated in PowerToys.

**Comment by lifeBalance** [comment]
Hm, I just checked PowerToys, also a cool project but none of the tools there are as essential as this one. Sure there are a couple of things to polish, like the transitions of wallpapers, when I use my 4 fingers I see the same wall paper, and changing the shortcuts it's a bit difficult.
But something that's easy to change is to write documentation about what your program does (and where it fails) If you check the powertoys project, there's extensive documentation with pics and all that.
Anyways, the app starts after I reboot, but do you know how I can get rid of the window that pops up asking me to authorize it? (I'm a Windows newbie)

**Comment by ViRb3** [comment]
The screenshots are tracked in #4, but I've not had the time to make them - contributions welcome. Additional documentation is also welcome. I've just not had the time to work on this project at all lately.

What pop up are you referring to? If it's the UAC prompt (for run as administrator), then your only current option is to disable the run as administrator option. Hiding that prompt will require a service that I haven't had the time to write. If you're getting a "file downloaded from the internet" prompt, you can disable that from the file properties (right click - properties).
