### ISSUE TITLE
Unbind of Left Ctrl + z

### ISSUE THREAD

**Issue by KlumpenM** [ViRb3/SylphyHornEx#18]
I've just downloaded SylphyHorn, and can't seem to unbind "Left Ctrl+z" shortcut. So every time I try to undo it just switches to the next left window.

Best Regards
KlumpenM

**Comment by ViRb3** [comment]
Nothing is bound to Ctrl + Z. The keybind is actually Ctrl + Win + Z, but because of a bug, when unlocking the computer the Win button stays pressed. To fix it, simply press the Win button once after unlocking your computer.

**Comment by ViRb3** [comment]
The issue is: #8
