### ISSUE TITLE
Broken on Insider "Dev" channel.

### ISSUE THREAD

**Issue by phyllisstein** [ViRb3/SylphyHornEx#26]
Hi there. I've become very attached to SylphyHornEx since giving Windows another shot---thanks for all the work you've put into it. The only challenge I've run into is some difficulty using it with the "Dev" Insider channel (currently build 21277).

The application starts up, and I can access its settings. I run into trouble when I try to use any of its custom features. It seems as though the keyboard shortcuts aren't responding; I also don't see notifications on switching virtual desktops, and the active desktop number is not showing in the taskbar. All was well under the "Beta" build channel.

I know the "Dev" channel is considered unstable, so I'm certainly content to sit tight for a while. I'm also happy to furnish any additional debugging info that might be useful. It's been a _long_ minute since I used a Windows machine, but if you can point me in the right direction I'll grab whatever logs or crash reports I have.

Thanks so much for any guidance you can offer.

**Comment by NorthWindH** [comment]
I'm seeing a similar set of issues on build 21318.1000

Please let me know if I can provide any logs or other assistance to diagnose the issue

**Comment by ViRb3** [comment]
I cannot afford to test on insider releases, so please open an issue if this issue persists on a stable release.
