### ISSUE TITLE
Reorder / rearrange desktops

### ISSUE THREAD

**Issue by LoganDark** [ViRb3/SylphyHornEx#35]
Where is this, how can I find it? The only thing I can find is moving individual windows to a different desktop, not swapping the contents of two desktops. If this feature doesn't exist, isn't the repository description a bit misleading?

**Comment by ViRb3** [comment]
Yes, it does exist. From the README:

> Reorder virtual desktops
(default key combination: Shift + Ctrl + Win + ← or →)

From the app:

![image](https://user-images.githubusercontent.com/2650170/123555953-b822b480-d780-11eb-8c97-67f828d90c96.png)
